/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsPartidaIdRouteImport } from './routes/stats.$partidaId'
import { Route as RankingGrupoIdRouteImport } from './routes/ranking.$grupoId'
import { Route as PartidaPartidaIdRouteImport } from './routes/partida.$partidaId'
import { Route as GruposGrupoIdRouteImport } from './routes/grupos/$grupoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPartidaIdRoute = StatsPartidaIdRouteImport.update({
  id: '/stats/$partidaId',
  path: '/stats/$partidaId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingGrupoIdRoute = RankingGrupoIdRouteImport.update({
  id: '/ranking/$grupoId',
  path: '/ranking/$grupoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaPartidaIdRoute = PartidaPartidaIdRouteImport.update({
  id: '/partida/$partidaId',
  path: '/partida/$partidaId',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposGrupoIdRoute = GruposGrupoIdRouteImport.update({
  id: '/grupos/$grupoId',
  path: '/grupos/$grupoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/partida/$partidaId': typeof PartidaPartidaIdRoute
  '/ranking/$grupoId': typeof RankingGrupoIdRoute
  '/stats/$partidaId': typeof StatsPartidaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/partida/$partidaId': typeof PartidaPartidaIdRoute
  '/ranking/$grupoId': typeof RankingGrupoIdRoute
  '/stats/$partidaId': typeof StatsPartidaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/partida/$partidaId': typeof PartidaPartidaIdRoute
  '/ranking/$grupoId': typeof RankingGrupoIdRoute
  '/stats/$partidaId': typeof StatsPartidaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grupos/$grupoId'
    | '/partida/$partidaId'
    | '/ranking/$grupoId'
    | '/stats/$partidaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grupos/$grupoId'
    | '/partida/$partidaId'
    | '/ranking/$grupoId'
    | '/stats/$partidaId'
  id:
    | '__root__'
    | '/'
    | '/grupos/$grupoId'
    | '/partida/$partidaId'
    | '/ranking/$grupoId'
    | '/stats/$partidaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GruposGrupoIdRoute: typeof GruposGrupoIdRoute
  PartidaPartidaIdRoute: typeof PartidaPartidaIdRoute
  RankingGrupoIdRoute: typeof RankingGrupoIdRoute
  StatsPartidaIdRoute: typeof StatsPartidaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$partidaId': {
      id: '/stats/$partidaId'
      path: '/stats/$partidaId'
      fullPath: '/stats/$partidaId'
      preLoaderRoute: typeof StatsPartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/$grupoId': {
      id: '/ranking/$grupoId'
      path: '/ranking/$grupoId'
      fullPath: '/ranking/$grupoId'
      preLoaderRoute: typeof RankingGrupoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$partidaId': {
      id: '/partida/$partidaId'
      path: '/partida/$partidaId'
      fullPath: '/partida/$partidaId'
      preLoaderRoute: typeof PartidaPartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$grupoId': {
      id: '/grupos/$grupoId'
      path: '/grupos/$grupoId'
      fullPath: '/grupos/$grupoId'
      preLoaderRoute: typeof GruposGrupoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GruposGrupoIdRoute: GruposGrupoIdRoute,
  PartidaPartidaIdRoute: PartidaPartidaIdRoute,
  RankingGrupoIdRoute: RankingGrupoIdRoute,
  StatsPartidaIdRoute: StatsPartidaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
